<?php

namespace Database\Seeders;

use App\Models\File;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Michel Motta da Silva',
                'email' => 'michel.motta@ufms.br',
                'expertise' => 'Desenvolvedor',
                'cpf' => '044.484.181-46',
                'username' => 'michel.motta',
                'active' => true,
                'biography' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consequat, nibh dignissim luctus consectetur, felis leo viverra sapien, id porttitor lorem est et lectus. Phasellus erat augue, tincidunt quis tortor ac, blandit pretium erat. Vestibulum placerat sapien turpis, at blandit turpis facilisis id. Suspendisse nunc dui, facilisis at egestas ac, viverra et massa.',
                'password' =>  Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'João Coordenador',
                'email' => 'coordenador@ufms.br',
                'expertise' => 'Cardiologista',
                'cpf' => '163.127.940-83',
                'username' => 'coordenador',
                'active' => true,
                'biography' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consequat, nibh dignissim luctus consectetur, felis leo viverra sapien, id porttitor lorem est et lectus. Phasellus erat augue, tincidunt quis tortor ac, blandit pretium erat. Vestibulum placerat sapien turpis, at blandit turpis facilisis id. Suspendisse nunc dui, facilisis at egestas ac, viverra et massa.',
                'password' =>  Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Pedro Professor',
                'email' => 'professor@ufms.br',
                'expertise' => 'Cardiologista',
                'cpf' => '969.944.580-75',
                'username' => 'professor',
                'active' => true,
                'biography' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consequat, nibh dignissim luctus consectetur, felis leo viverra sapien, id porttitor lorem est et lectus. Phasellus erat augue, tincidunt quis tortor ac, blandit pretium erat. Vestibulum placerat sapien turpis, at blandit turpis facilisis id. Suspendisse nunc dui, facilisis at egestas ac, viverra et massa.',
                'password' =>  Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Maria Estudante',
                'email' => 'estudante@ufms.br',
                'cpf' => '693.672.990-87',
                'username' => 'estudante',
                'active' => true,
                'password' =>  Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Lucas Almeida Ribeiro',
                'email' => 'lucas.ribeiro@ufms.br',
                'cpf' => '101.202.303-01',
                'username' => 'lucas.ribeiro',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Juliana Barbosa Correia',
                'email' => 'juliana.correia@ufms.br',
                'cpf' => '202.303.404-02',
                'username' => 'juliana.correia',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Matheus Castro e Silva',
                'email' => 'matheus.silva@ufms.br',
                'cpf' => '303.404.505-03',
                'username' => 'matheus.silva',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Beatriz Dias Ferreira',
                'email' => 'beatriz.ferreira@ufms.br',
                'cpf' => '404.505.606-04',
                'username' => 'beatriz.ferreira',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Guilherme Gomes Azevedo',
                'email' => 'guilherme.azevedo@ufms.br',
                'cpf' => '505.606.707-05',
                'username' => 'guilherme.azevedo',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Larissa Lima de Souza',
                'email' => 'larissa.souza@ufms.br',
                'cpf' => '606.707.808-06',
                'username' => 'larissa.souza',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Rafael Martins Cardoso',
                'email' => 'rafael.cardoso@ufms.br',
                'cpf' => '707.808.909-07',
                'username' => 'rafael.cardoso',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Sofia Moreira Pinto',
                'email' => 'sofia.pinto@ufms.br',
                'cpf' => '808.909.101-08',
                'username' => 'sofia.pinto',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Thiago Nogueira Rocha',
                'email' => 'thiago.rocha@ufms.br',
                'cpf' => '909.101.202-09',
                'username' => 'thiago.rocha',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Valentina Oliveira Santos',
                'email' => 'valentina.santos@ufms.br',
                'cpf' => '121.232.343-10',
                'username' => 'valentina.santos',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Arthur Pereira da Costa',
                'email' => 'arthur.costa@ufms.br',
                'cpf' => '232.343.454-11',
                'username' => 'arthur.costa',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Clara Rodrigues Alves',
                'email' => 'clara.alves@ufms.br',
                'cpf' => '343.454.565-12',
                'username' => 'clara.alves',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Davi Teixeira Mendes',
                'email' => 'davi.mendes@ufms.br',
                'cpf' => '454.565.676-13',
                'username' => 'davi.mendes',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Eloá Fernandes Barros',
                'email' => 'eloa.barros@ufms.br',
                'cpf' => '565.676.787-14',
                'username' => 'eloa.barros',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Francisco Jesus Neves',
                'email' => 'francisco.neves@ufms.br',
                'cpf' => '676.787.898-15',
                'username' => 'francisco.neves',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Helena Sousa Campos',
                'email' => 'helena.campos@ufms.br',
                'cpf' => '787.898.909-16',
                'username' => 'helena.campos',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Ícaro Duarte Ramos',
                'email' => 'icaro.ramos@ufms.br',
                'cpf' => '898.909.010-17',
                'username' => 'icaro.ramos',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Joana Viana Cunha',
                'email' => 'joana.cunha@ufms.br',
                'cpf' => '909.010.121-18',
                'username' => 'joana.cunha',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Leonardo Xavier Pires',
                'email' => 'leonardo.pires@ufms.br',
                'cpf' => '010.121.232-19',
                'username' => 'leonardo.pires',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'Manuela Silveira Farias',
                'email' => 'manuela.farias@ufms.br',
                'cpf' => '121.232.343-20',
                'username' => 'manuela.farias',
                'active' => true,
                'password' => Hash::make('505426'),
                'file_id' => 9,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
        ];

        foreach ($users as $user) {
            User::factory()->create($user);
        }

        $files = File::all();

        foreach ($files as $file) {
            $file->user_id = 1;
            $file->save();
        }
    }
}
